// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elznpizosxbhrwzrluix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsem5waXpvc3hiaHJ3enJsdWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTE5MDUsImV4cCI6MjA2MDk2NzkwNX0.uv6Awa-8urLI-BwAQTpKPLWwA06sWOVAP-G9-vNOvwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);